sudo: required
services:
  - docker

notifications:
  email: false

before_install:
  - docker build -t nursh/restaurant-application -f ./client/Dockerfile.dev ./client

script:
  - docker run nursh/restaurant-application npm test -- --coverage

after_success:
  - docker build -t nursh/resapp-client ./client
  - docker build -t nursh/resapp-nginx ./nginx
  - docker build -t nursh/resapp-server ./server
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push nursh/resapp-client
  - docker push nursh/resapp-nginx
  - docker push nursh/resapp-server

deploy: 
  provider: elasticbeanstalk
  region: us-east-2
  app: Ruby-Continental | Restaurant 
  env: MRubyContinental-env
  bucket_name: elasticbeanstalk-us-east-2-360884463829
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY 
