sudo: required
services:
  - docker

before_install:
  - docker build -t nursh/restaurant-app -f ./client/Dockerfile.env ./client

script:
  - docker run nursh/res-app npm --test --coverage

after_success:
  - docker build -t nursh/restaurant-client ./client
  - docker build -t nursh/restaurant-nginx ./nginx
  - docker build -t nursh/restaurant-server ./server
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push nursh/restaurant-client
  - docker push nursh/restaurant-nginx
  - docker push nursh/restaurant-server
