version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:80"
      - "4000:80"
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    env_file:
      - ./.env
  graphql:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
